name: iconified_flutter
description: "100+ open source icon sets for flutter to make you app more beautiful"
version: 0.0.6
homepage: "https://github.com/volkanakbayir/iconified_flutter"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
